//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessRoom.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int idAttendance { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> countСlasses { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
