//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessRoom.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Attendance = new HashSet<Attendance>();
        }
    
        public int idClient { get; set; }
        public string nameClient { get; set; }
        public string surnameClient { get; set; }
        public string middleNameClient { get; set; }
        public Nullable<int> idSeasonTicket { get; set; }
        public Nullable<int> idTrainer { get; set; }
        public string number { get; set; }
        public Nullable<int> idSchedule { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual SeasonTicket SeasonTicket { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
